// The licences of the HTML and CSS passes' installed npm tree (node_modules of
// `npm ci --omit=dev`). Fails on any licence outside the allowlist (no copyleft and no named
// exceptions), and writes deploy/scanner/licenses/WEBLINT-DEPENDENCIES.txt: each package's name,
// version, licence and licence files, as shipped in /opt/qualor/weblint. run.test.ts checks the
// committed file against a fresh run over the local install.
//   node tools/analyzers/weblint/licences.mjs [node_modules dir] [out file]
import { readdirSync, readFileSync, writeFileSync, existsSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ALLOWED = new Set([
  'MIT',
  'MIT-0',
  'ISC',
  'BSD-2-Clause',
  'BSD-3-Clause',
  'Apache-2.0',
  '0BSD',
  'CC0-1.0',
  'BlueOak-1.0.0',
  'Python-2.0',
]);

/** Why `name`'s licence is not acceptable, or null when it is. */
export function licenceProblem(name, licence) {
  if (typeof licence !== 'string' || licence === '') return `${name}: no licence declared`;
  if (ALLOWED.has(licence)) return null;
  return `${name}: ${licence} is not an allowed licence`;
}

function licenceOf(pkg) {
  if (typeof pkg.license === 'string') return pkg.license;
  if (pkg.license?.type) return pkg.license.type;
  if (Array.isArray(pkg.licenses)) return pkg.licenses.map((l) => l.type ?? l).join(' OR ');
  return undefined;
}

/** Every package directory under `dir` (node_modules), nested ones included, sorted. */
function packageDirs(dir) {
  const out = [];
  const visit = (modules) => {
    if (!existsSync(modules)) return;
    for (const entry of readdirSync(modules, { withFileTypes: true })) {
      if (!entry.isDirectory() || entry.name.startsWith('.')) continue;
      const full = path.join(modules, entry.name);
      if (entry.name.startsWith('@')) {
        for (const scoped of readdirSync(full, { withFileTypes: true })) {
          if (scoped.isDirectory()) add(path.join(full, scoped.name));
        }
      } else add(full);
    }
  };
  const add = (pkgDir) => {
    if (existsSync(path.join(pkgDir, 'package.json'))) out.push(pkgDir);
    visit(path.join(pkgDir, 'node_modules'));
  };
  visit(dir);
  return out.sort(compareStrings);
}

/** Code-unit order, the same on every platform (no locale). */
function compareStrings(a, b) {
  if (a === b) return 0;
  return a < b ? -1 : 1;
}

/** The text of WEBLINT-DEPENDENCIES.txt for the tree at `dir`; throws on a disallowed licence. */
export function dependencyNotice(dir) {
  const problems = [];
  const sections = [];
  for (const pkgDir of packageDirs(dir)) {
    const pkg = JSON.parse(readFileSync(path.join(pkgDir, 'package.json'), 'utf8'));
    const licence = licenceOf(pkg);
    const problem = licenceProblem(pkg.name, licence);
    if (problem) problems.push(problem);
    const where = path.relative(dir, pkgDir).split(path.sep).join('/');
    const files = readdirSync(pkgDir)
      .filter((f) => /^(licen[cs]e|copying|notice)/i.test(f))
      .sort();
    const texts = files.map(
      (f) =>
        `--- ${f}\n${readFileSync(path.join(pkgDir, f), 'utf8').replace(/\r\n/g, '\n').trimEnd()}\n`,
    );
    sections.push(
      [
        `${pkg.name} ${pkg.version} (${licence ?? 'no licence'})`,
        `node_modules/${where}`,
        '',
        ...(texts.length > 0
          ? texts
          : [`(the package ships no licence file; its package.json declares ${licence})\n`]),
      ].join('\n'),
    );
  }
  if (problems.length > 0) throw new Error(`disallowed licences:\n${problems.join('\n')}`);
  return [
    'The npm packages of Qualor’s HTML and CSS linters in /opt/qualor/weblint (stylelint 17.15.0',
    'with the configs Qualor bundles, and HTMLHint 1.9.2, and what they depend on, as installed by',
    '`npm ci --omit=dev` from tools/analyzers/weblint/package-lock.json), each with the licence',
    'files it ships. Generated by tools/analyzers/weblint/licences.mjs; do not edit.',
    '',
    ...sections.map((s) => `${'='.repeat(78)}\n${s}`),
  ].join('\n');
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const here = path.dirname(fileURLToPath(import.meta.url));
  const dir = process.argv[2] ?? path.join(here, 'node_modules');
  const out =
    process.argv[3] ?? path.join(here, '../../../deploy/scanner/licenses/WEBLINT-DEPENDENCIES.txt');
  try {
    writeFileSync(out, dependencyNotice(dir));
    process.stdout.write(`licences.mjs: wrote ${out}\n`);
  } catch (err) {
    process.stderr.write(`licences.mjs: ${err.message}\n`);
    process.exit(1);
  }
}
