import type { components, paths } from './schema';

/**
 * Shorthands over the generated OpenAPI types (`schema.ts`, regenerated by
 * `pnpm --filter @qualor/ui api` from server/openapi.json). The UI never declares an API shape by
 * hand (brief §5.7: the UI talks to the server only through the generated client).
 */
export type Problem = components['schemas']['Problem'];

type JsonOf<R> = R extends { content: { 'application/json': infer T } } ? T : never;

/** The JSON body of an operation's 200 or 201 response. */
export type ResponseBody<P extends keyof paths, M extends keyof paths[P]> = paths[P][M] extends {
  responses: infer R;
}
  ? R extends { 200: infer Ok }
    ? JsonOf<Ok>
    : R extends { 201: infer Created }
      ? JsonOf<Created>
      : never
  : never;

/** One item of a keyset-paginated list response (`{ items, nextCursor }`). */
export type ItemOf<P extends keyof paths> =
  ResponseBody<P, 'get' & keyof paths[P]> extends { items: (infer T)[] } ? T : never;

/** The JSON request body of an operation. */
export type RequestBody<P extends keyof paths, M extends keyof paths[P]> = paths[P][M] extends {
  requestBody?: { content: { 'application/json': infer B } };
}
  ? B
  : never;

export type Me = ResponseBody<'/api/v0/auth/me', 'get'>;
/** `GET /auth/methods` (sso-scim.md §10): the password policy and the SSO providers. */
export type AuthMethods = ResponseBody<'/api/v0/auth/methods', 'get'>;
export type SsoProvider = AuthMethods['providers'][number];
export type Organization = ItemOf<'/api/v0/organizations'>;

/** A role grant on one project (rbac-audit.md §16, `GET /projects/{id}/members`). */
export type ProjectGrant = ItemOf<'/api/v0/projects/{id}/members'>;
/** The roles a project grant may carry: `admin` is organisation-wide only (§3.2). */
export type GrantRole = ProjectGrant['role'];
