// Writes packages/shared/rules/go-rules.json (plan 9C): the rule ids of the pinned Go analyzers —
// staticcheck's checks (`staticcheck -list-checks`), go vet's analyzers (`go tool vet help`) and
// gosec's rules (`gosec -h`) — and the versions they came from. Ids only, no rule text.
//   node tools/analyzers/go-rules.mjs [go] [staticcheck] [gosec]
import { execFileSync, spawnSync } from 'node:child_process';
import { mkdtempSync, rmSync, writeFileSync } from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

export function parseStaticcheckChecks(text) {
  return [...text.matchAll(/^((?:SA|S|ST|QF|U)\d{4}) /gm)].map((m) => m[1]).sort();
}

export function parseVetAnalyzers(text) {
  const start = text.indexOf('Registered analyzers:');
  const end = text.indexOf('By default all analyzers are run.');
  if (start < 0 || end < start) throw new Error('unexpected `go tool vet help` output');
  return [...text.slice(start, end).matchAll(/^ {4}([a-z][a-z0-9]*)\s/gm)].map((m) => m[1]).sort();
}

export function parseGosecRules(text) {
  return [...new Set([...text.matchAll(/^\s+(G\d{3}):/gm)].map((m) => m[1]))].sort();
}

export function buildTable(bins) {
  // An empty directory and no inherited Go settings: nothing of the caller's checkout or CI.
  const dir = mkdtempSync(path.join(os.tmpdir(), 'go-rules-'));
  try {
    const env = {
      PATH: process.env.PATH ?? '',
      HOME: dir,
      GOTOOLCHAIN: 'local',
      GOENV: 'off',
      GOFLAGS: '',
      GOPROXY: 'off',
    };
    const run = (cmd, args) => {
      const r = spawnSync(cmd, args, {
        cwd: dir,
        env,
        encoding: 'utf8',
        maxBuffer: 16 * 1024 * 1024,
      });
      return `${r.stdout ?? ''}${r.stderr ?? ''}`;
    };
    const go = /go version go(\S+) /.exec(
      execFileSync(bins.go, ['version'], { cwd: dir, env, encoding: 'utf8' }),
    )?.[1];
    const sc = /^staticcheck (\d+\.\d+\.\d+)/.exec(run(bins.staticcheck, ['-version']))?.[1];
    const gs = /^Version: (\d+\.\d+\.\d+)$/m.exec(run(bins.gosec, ['-version']))?.[1];
    if (!go || !sc || !gs) throw new Error('a tool printed no version');
    return {
      go,
      staticcheck: {
        version: sc,
        checks: parseStaticcheckChecks(run(bins.staticcheck, ['-list-checks'])),
      },
      govet: { analyzers: parseVetAnalyzers(run(bins.go, ['tool', 'vet', 'help'])) },
      gosec: { version: gs, rules: parseGosecRules(run(bins.gosec, ['-h'])) },
    };
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
}

if (
  process.argv[1] !== undefined &&
  path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)
) {
  const [go = 'go', staticcheck = 'staticcheck', gosec = 'gosec'] = process.argv.slice(2);
  const t = buildTable({ go, staticcheck, gosec });
  const out = path.join(
    path.dirname(fileURLToPath(import.meta.url)),
    '../../packages/shared/rules/go-rules.json',
  );
  const doc = {
    $comment: `Generated by tools/analyzers/go-rules.mjs from Go ${t.go}, staticcheck ${t.staticcheck.version} and gosec ${t.gosec.version}: rule ids only (staticcheck MIT, Go BSD-3-Clause, gosec Apache-2.0). Regenerate on every pin bump of tools/analyzers/install-go.sh.`,
    ...t,
  };
  writeFileSync(out, `${JSON.stringify(doc, null, 2)}\n`);
  process.stdout.write(
    `${t.staticcheck.checks.length} checks, ${t.govet.analyzers.length} analyzers, ${t.gosec.rules.length} rules -> ${out}\n`,
  );
}
