import { existsSync, readFileSync } from 'node:fs';
import { describe, expect, it } from 'vitest';
import { RUBOCOP_VERSION } from '../../packages/shared/src/rules/rubocop';
import { rubocopTables, tableFrom } from './rubocop-cops';

const DIR = '/opt/qualor/rubocop';
const committed = (name: string) =>
  JSON.parse(readFileSync(`packages/shared/rules/${name}`, 'utf8')) as unknown;

describe('rubocop-cops.ts', () => {
  it('validates run.rb --cops and sorts the cops', () => {
    const t = tableFrom({
      version: '1.91.0',
      targetRubies: ['3.4', '4.0'],
      cops: { 'Style/B': 'pending', 'Lint/A': 'enabled' },
    });
    expect(Object.keys(t.cops)).toEqual(['Lint/A', 'Style/B']);
    expect(t.$comment).toMatch(/Generated by tools\/analyzers\/rubocop-cops\.ts/);
    expect(() => tableFrom({ version: '1', targetRubies: [], cops: {} })).toThrow();
    expect(() =>
      tableFrom({ version: '1', targetRubies: ['4.0'], cops: { lint: 'enabled' } }),
    ).toThrow();
    expect(() =>
      tableFrom({ version: '1', targetRubies: ['4.0'], cops: { 'Lint/A': 'maybe' } }),
    ).toThrow();
  });
});

describe.runIf(existsSync(`${DIR}/run.rb`) || process.env['QUALOR_REQUIRE_ANALYZERS'] === '1')(
  'the committed RuboCop tables',
  () => {
    it('are what the pinned RuboCop says', () => {
      const t = rubocopTables(DIR);
      expect(t.table.version).toBe(RUBOCOP_VERSION);
      expect(committed('rubocop-cops.json')).toEqual(t.table);
      expect(committed('rubocop-keys.json')).toEqual(t.keys);
      expect(committed('rubocop-default-keys.json')).toEqual(t.defaultKeys);
    });
  },
);
