// Generates the RuboCop tables Qualor commits (plan 9B, import-sonarqube.md §6.4), RuboCop's own
// facts (MIT), names and states only:
//   packages/shared/rules/rubocop-cops.json          every cop, its default state, the target Rubies RuboCop parses
//   packages/shared/rules/rubocop-keys.json          every cop name
//   packages/shared/rules/rubocop-default-keys.json  the cops qualor-default runs
// Run with the pinned RuboCop pass (tools/analyzers/install-rubocop.sh), e.g. in the toolbox:
//   pnpm exec tsx tools/analyzers/rubocop-cops.ts [/opt/qualor/rubocop]
import { spawnSync } from 'node:child_process';
import { writeFileSync } from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  qualorDefaultCops,
  type RubocopTable,
  rubocopTableSchema,
} from '../../packages/shared/src/rules/rubocop-default';

export type { RubocopTable };

const COMMENT =
  'Generated by tools/analyzers/rubocop-cops.ts from the pinned RuboCop (run.rb --cops): RuboCop’s own facts (MIT), cop names, default states and the target Ruby versions it parses. Do not edit.';

/**
 * `run.rb --cops` → the committed table, checked by the same schema packages/shared reads it
 * with (rubocop-default.ts) and sorted by cop name.
 */
export function tableFrom(json: unknown): RubocopTable {
  const j = rubocopTableSchema.omit({ $comment: true }).parse(json);
  const cops = Object.entries(j.cops).sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0));
  return rubocopTableSchema.parse({
    $comment: COMMENT,
    version: j.version,
    targetRubies: j.targetRubies,
    cops: Object.fromEntries(cops),
  });
}

export function rubocopTables(dir: string): {
  table: RubocopTable;
  keys: string[];
  defaultKeys: string[];
} {
  const r = spawnSync(path.join(dir, 'ruby', 'bin', 'ruby'), [path.join(dir, 'run.rb'), '--cops'], {
    encoding: 'utf8',
    maxBuffer: 16 * 1024 * 1024,
    timeout: 120_000,
    env: { PATH: process.env['PATH'] ?? '', HOME: os.tmpdir(), LC_ALL: 'C.UTF-8' },
  });
  if (r.status !== 0) throw new Error(`run.rb --cops exited ${r.status}: ${r.stderr}`);
  const table = tableFrom(JSON.parse(r.stdout));
  return {
    table,
    keys: Object.keys(table.cops),
    defaultKeys: qualorDefaultCops(new Map(Object.entries(table.cops))),
  };
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const t = rubocopTables(process.argv[2] ?? '/opt/qualor/rubocop');
  const out = (name: string, value: unknown) =>
    writeFileSync(path.join('packages/shared/rules', name), `${JSON.stringify(value, null, 2)}\n`);
  out('rubocop-cops.json', t.table);
  out('rubocop-keys.json', t.keys);
  out('rubocop-default-keys.json', t.defaultKeys);
  console.log(`${t.keys.length} cops, ${t.defaultKeys.length} run by qualor-default`);
}
