// Writes packages/shared/rules/swiftlint-rules.json (plan 8F): each rule of the installed SwiftLint
// with its kind, whether it is opt-in, needs SourceKit (the table's column, plus every rule a lint
// with all rules enabled skips for want of SourceKit), is an analyzer rule, or is enabled by
// default. Only identifiers and SwiftLint's own classification (MIT), no rule text.
//   node tools/analyzers/swiftlint-rules.mjs [path/to/swiftlint]
import { execFileSync, spawnSync } from 'node:child_process';
import { mkdtempSync, rmSync, writeFileSync } from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

export function parseRulesTable(text) {
  const rules = {};
  let header = null;
  for (const line of text.split('\n')) {
    if (!line.startsWith('|')) continue;
    const cells = line
      .split('|')
      .slice(1, -1)
      .map((c) => c.trim());
    if (header === null) {
      header = cells;
      continue;
    }
    const row = Object.fromEntries(header.map((h, i) => [h, cells[i] ?? '']));
    rules[row['identifier']] = {
      kind: row['kind'],
      optIn: row['opt-in'] === 'yes',
      sourceKit: row['uses sourcekit'] === 'yes',
      analyzer: row['analyzer'] === 'yes',
      enabledByDefault: row['enabled in your config'] === 'yes',
    };
  }
  return rules;
}

export function parseSkipped(stderr) {
  return [
    ...stderr.matchAll(/Skipping enabled rule '([a-z0-9_]+)' because it requires SourceKit/g),
  ].map((m) => m[1]);
}

/**
 * Marks every rule the all-rules lint skipped for want of SourceKit. That list comes from
 * SwiftLint's stderr wording ("Skipping enabled rule '…' because it requires SourceKit"), so a lint
 * that names none while the table has SourceKit rules means the wording changed: fail rather than
 * write a table that runs rules the static binary cannot (final review minor 3).
 */
export function markSourceKit(rules, stderr) {
  const skipped = parseSkipped(stderr);
  const expected = Object.values(rules).filter((r) => r.sourceKit).length;
  if (skipped.length === 0 && expected > 0) {
    throw new Error(
      `the all-rules lint named no rule skipped for want of SourceKit, but the table has ${expected}: has SwiftLint's "Skipping enabled rule" wording changed?`,
    );
  }
  for (const id of skipped) if (rules[id]) rules[id].sourceKit = true;
  return rules;
}

export function buildTable(swiftlint) {
  // An empty directory: `swiftlint rules` must not read a .swiftlint.yml of the caller.
  const dir = mkdtempSync(path.join(os.tmpdir(), 'swiftlint-rules-'));
  try {
    const env = { PATH: process.env.PATH ?? '', SWIFTLINT_DISABLE_SOURCEKIT: '1' };
    const version = execFileSync(swiftlint, ['version'], {
      cwd: dir,
      env,
      encoding: 'utf8',
    }).trim();
    const table = execFileSync(swiftlint, ['rules', '--default-config'], {
      cwd: dir,
      env,
      encoding: 'utf8',
      maxBuffer: 16 * 1024 * 1024,
    });
    writeFileSync(path.join(dir, 'a.swift'), 'let value = 1\n');
    const lint = spawnSync(
      swiftlint,
      ['lint', '--quiet', '--no-cache', '--enable-all-rules', 'a.swift'],
      { cwd: dir, env, encoding: 'utf8' },
    );
    const rules = markSourceKit(parseRulesTable(table), lint.stderr ?? '');
    const sorted = Object.fromEntries(Object.entries(rules).sort(([a], [b]) => a.localeCompare(b)));
    return { version, rules: sorted };
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const here = path.dirname(fileURLToPath(import.meta.url));
  const out = path.join(here, '../../packages/shared/rules/swiftlint-rules.json');
  const { version, rules } = buildTable(process.argv[2] ?? 'swiftlint');
  const doc = {
    $comment: `Generated by tools/analyzers/swiftlint-rules.mjs from SwiftLint ${version}'s own \`swiftlint rules\` (MIT): identifiers and SwiftLint's classification only. Regenerate on every SWIFTLINT_VERSION bump.`,
    version,
    rules,
  };
  writeFileSync(out, `${JSON.stringify(doc, null, 2)}\n`);
  process.stdout.write(`${Object.keys(rules).length} rules of SwiftLint ${version} -> ${out}\n`);
}
