{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "qualor.secretName" . }}
  labels:
    {{- include "qualor.labels" . | nindent 4 }}
type: Opaque
data:
  QUALOR_SECRET_KEY: {{ .Values.secrets.secretKey | b64enc | quote }}
  QUALOR_BOOTSTRAP_ADMIN_PASSWORD: {{ .Values.secrets.bootstrapAdminPassword | b64enc | quote }}
{{- end }}
{{- if and (eq .Values.database.mode "bundled") (not .Values.database.bundled.existingSecret) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "qualor.postgresSecretName" . }}
  labels:
    {{- include "qualor.labels" . | nindent 4 }}
type: Opaque
data:
  POSTGRES_PASSWORD: {{ .Values.database.bundled.password | b64enc | quote }}
{{- end }}
