/**
 * A test certificate authority and a server certificate it signed, for 127.0.0.1 and localhost,
 * valid from 2000 to 2100 (generated once with openssl, EC P-256). Test data only: the key is
 * published here on purpose and protects nothing. Kept in a module rather than in .pem files so the
 * compiled Bun smoke binary carries them too.
 */
export const TEST_CA_PEM = `-----BEGIN CERTIFICATE-----
MIIBmDCCAT+gAwIBAgIUbOsvT9Kyqm8vB/pXrjWAoMYxM0UwCgYIKoZIzj0EAwIw
GTEXMBUGA1UEAwwOUXVhbG9yIFRlc3QgQ0EwIBcNMDAwMTAxMDAwMDAwWhgPMjEw
MDAxMDEwMDAwMDBaMBkxFzAVBgNVBAMMDlF1YWxvciBUZXN0IENBMFkwEwYHKoZI
zj0CAQYIKoZIzj0DAQcDQgAEWXY9s2Wb/5IKbPMc+Y5u9gCa5AI8NiKOtTmSrkUg
XUuXF7mpUzr+b18plfZ/McbVnD+jcFZynA+DjpnJCQ6zrKNjMGEwHQYDVR0OBBYE
FGAPr61LFNeEUDKlq1C8rOWl/8hcMB8GA1UdIwQYMBaAFGAPr61LFNeEUDKlq1C8
rOWl/8hcMA8GA1UdEwEB/wQFMAMBAf8wDgYDVR0PAQH/BAQDAgEGMAoGCCqGSM49
BAMCA0cAMEQCIGXDTFJfuyj/rSfj8W9FHI5/JtRdbXmoRacQF14dgNo7AiA/QYsE
0nlGz37NpT1aJNgCSaJxJxJkVYBTO6id/q5fXQ==
-----END CERTIFICATE-----
`;

export const TEST_SERVER_CERT_PEM = `-----BEGIN CERTIFICATE-----
MIIBwjCCAWegAwIBAgIUCIjr1J9/emE97KmjMXTM0MCnL9UwCgYIKoZIzj0EAwIw
GTEXMBUGA1UEAwwOUXVhbG9yIFRlc3QgQ0EwIBcNMDAwMTAxMDAwMDAwWhgPMjEw
MDAxMDEwMDAwMDBaMBQxEjAQBgNVBAMMCTEyNy4wLjAuMTBZMBMGByqGSM49AgEG
CCqGSM49AwEHA0IABCEqmshsloLnTXM99eWD/j6chUwKQpijy2JH46CkhHVyGlle
d1S0F4iqB+AvD4ZwARcB6zGDCPYu7UaK2uFESqejgY8wgYwwGgYDVR0RBBMwEYcE
fwAAAYIJbG9jYWxob3N0MAkGA1UdEwQCMAAwDgYDVR0PAQH/BAQDAgeAMBMGA1Ud
JQQMMAoGCCsGAQUFBwMBMB0GA1UdDgQWBBT+M4j4RJSiw4Z1tHw3cmNBdH+PuTAf
BgNVHSMEGDAWgBRgD6+tSxTXhFAypatQvKzlpf/IXDAKBggqhkjOPQQDAgNJADBG
AiEAzGOQLKcuOg4AKb7QlBl07mOSanhbq8A3PZt6uo3au10CIQCKgDpdBy2dssxL
Rczreuiw9Wu8WwhzNXPRUXL79SHjHA==
-----END CERTIFICATE-----
`;

export const TEST_SERVER_KEY_PEM = `-----BEGIN PRIVATE KEY-----
MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgN3lQy3RnVGeqbu0h
miNgGALNLmc3jjzC5o77K8qZuzehRANCAAQhKprIbJaC501zPfXlg/4+nIVMCkKY
o8tiR+OgpIR1chpZXndUtBeIqgfgLw+GcAEXAesxgwj2Lu1GitrhREqn
-----END PRIVATE KEY-----
`;
