import type { Permission } from './policy';

export type RouteRule =
  Permission | `list:${Permission}` | 'public' | 'authenticated' | 'self' | 'instance-admin';

/**
 * rbac-audit.md §3.4: every route of server/src/routes/ and its rule. The spec's table and this
 * object are equal (route-permissions.test.ts); every route checks its rule through a guarded
 * helper (route-permissions.sweep.test.ts).
 */
export const ROUTE_PERMISSIONS: Readonly<Record<string, RouteRule>> = Object.freeze({
  'GET /healthz': 'public',
  'GET /readyz': 'public',
  'GET /api/v0/openapi.json': 'public',
  'GET /api/v0/system/info': 'authenticated',
  'GET /api/v0/system/version': 'authenticated',
  'POST /auth/login': 'public',
  'GET /auth/methods': 'public',
  'POST /auth/logout': 'authenticated',
  'GET /auth/me': 'authenticated',
  'PUT /auth/me/password': 'self',
  'GET /users': 'instance-admin',
  'POST /users': 'instance-admin',
  'PATCH /users/:id': 'instance-admin',
  'GET /users/lookup': 'org.members.manage',
  'GET /tokens': 'self',
  'POST /tokens': 'self',
  'DELETE /tokens/:id': 'self',
  'GET /license': 'instance-admin',
  'PUT /license': 'instance-admin',
  'DELETE /license': 'instance-admin',
  'GET /system/llm': 'instance-admin',
  'PUT /system/llm': 'instance-admin',
  'POST /system/llm/test': 'instance-admin',
  'GET /organizations': 'list:org.read',
  'POST /organizations': 'instance-admin',
  'GET /organizations/:id/members': 'org.members.read',
  'PUT /organizations/:id/members/:userId': 'org.members.manage',
  'DELETE /organizations/:id/members/:userId': 'org.members.manage',
  'GET /organizations/:id/ai': 'org.read',
  'GET /projects': 'list:project.read',
  'POST /projects': 'org.projects.create',
  'GET /projects/by-key': 'project.read',
  'GET /projects/:id': 'project.read',
  'PATCH /projects/:id': 'project.settings',
  'DELETE /projects/:id': 'project.delete',
  'GET /projects/:id/members': 'org.members.read',
  'PUT /projects/:id/members/:userId': 'org.members.manage',
  'DELETE /projects/:id/members/:userId': 'org.members.manage',
  'GET /projects/:id/tokens': 'project.tokens.manage',
  'POST /projects/:id/tokens': 'project.tokens.manage',
  'DELETE /projects/:id/tokens/:tokenId': 'project.tokens.manage',
  'GET /projects/:id/branches': 'project.read',
  'DELETE /branches/:id': 'project.branches.delete',
  'POST /analyses': 'project.analyze',
  'GET /analyses/:id': 'project.read',
  'GET /branches/:id/analyses': 'project.read',
  'GET /projects/new-code-baseline': 'project.analyze',
  'GET /branches/:id/measures': 'project.read',
  'GET /branches/:id/measures/history': 'project.read',
  'GET /branches/:id/files': 'project.read',
  'GET /branches/:id/file': 'project.read',
  'GET /issues': 'project.read',
  'GET /issues/:id': 'project.read',
  'POST /issues/:id/transition': 'issue.triage',
  'POST /issues/bulk-transition': 'issue.triage',
  'PATCH /issues/:id': 'issue.triage',
  'GET /issues/:id/changelog': 'project.read',
  'POST /projects/:id/issue-status-import': 'project.issues.import',
  'GET /metrics': 'authenticated',
  'GET /rules': 'org.read',
  'GET /rules/:key': 'org.read',
  'GET /quality-gates': 'org.read',
  'POST /quality-gates': 'org.gates.manage',
  'GET /quality-gates/:id': 'org.read',
  'PATCH /quality-gates/:id': 'org.gates.manage',
  'DELETE /quality-gates/:id': 'org.gates.manage',
  'POST /quality-gates/:id/copy': 'org.gates.manage',
  'POST /quality-gates/:id/set-default': 'org.gates.manage',
  'POST /quality-gates/:id/conditions': 'org.gates.manage',
  'PATCH /quality-gates/:id/conditions/:condId': 'org.gates.manage',
  'DELETE /quality-gates/:id/conditions/:condId': 'org.gates.manage',
  'GET /quality-profiles': 'org.read',
  'POST /quality-profiles': 'org.profiles.manage',
  'GET /quality-profiles/:id': 'org.read',
  'PATCH /quality-profiles/:id': 'org.profiles.manage',
  'DELETE /quality-profiles/:id': 'org.profiles.manage',
  'POST /quality-profiles/:id/copy': 'org.profiles.manage',
  'POST /quality-profiles/:id/set-default': 'org.profiles.manage',
  'GET /quality-profiles/:id/rules': 'org.read',
  'PUT /quality-profiles/:id/rules/:ruleKey': 'org.profiles.manage',
  'DELETE /quality-profiles/:id/rules/:ruleKey': 'org.profiles.manage',
  'GET /projects/:id/quality-profiles': 'project.read',
  'PUT /projects/:id/quality-profiles/:language': 'project.settings',
  'GET /scm-connections': 'org.scm.manage',
  'POST /scm-connections': 'org.scm.manage',
  'PATCH /scm-connections/:id': 'org.scm.manage',
  'DELETE /scm-connections/:id': 'org.scm.manage',
  'POST /scm-connections/:id/test': 'org.scm.manage',
  'POST /api/v0/github/webhooks/:connectionId': 'public',
  'POST /issues/:id/ai/:feature': 'ai.use',
  'GET /ai-requests/:id': 'project.read',
  'POST /ai-requests/:id/post': 'ai.use',
  'GET /issues/:id/ai': 'project.read',
  'GET /webhooks': 'org.webhooks.manage',
  'POST /webhooks': 'org.webhooks.manage',
  'GET /webhooks/:id': 'org.webhooks.manage',
  'PATCH /webhooks/:id': 'org.webhooks.manage',
  'POST /webhooks/:id/regenerate-secret': 'org.webhooks.manage',
  'DELETE /webhooks/:id': 'org.webhooks.manage',
  'GET /webhooks/:id/deliveries': 'org.webhooks.manage',
  'POST /webhooks/:id/deliveries/:deliveryId/redeliver': 'org.webhooks.manage',
});

/** The helpers that resolve an object and ask the policy (rbac-audit.md §5). */
export const GUARDED_HELPERS = [
  'requireOrganizationAccess',
  'projectForUser',
  'projectForUpload',
  'branchForUser',
  'issueForUser',
  'analysisForPrincipal',
  'aiRequestFor',
  'gateFor',
  'profileFor',
  'connectionFor',
  'webhookFor',
  'ruleFor',
  'transitionIssues',
  'requestAi',
  'requireMembersManager',
] as const;

/** Helpers whose permission is fixed, so a route passes none. */
export const IMPLICIT_PERMISSIONS: Readonly<Record<string, Permission>> = Object.freeze({
  projectForUpload: 'project.analyze',
  analysisForPrincipal: 'project.read',
  connectionFor: 'org.scm.manage',
  webhookFor: 'org.webhooks.manage',
  ruleFor: 'org.read',
  transitionIssues: 'issue.triage',
  requestAi: 'ai.use',
  requireMembersManager: 'org.members.manage',
});

/** The SQL condition builder a `list:` rule's route must call. */
export const LIST_CONDITIONS: Readonly<Record<string, string>> = Object.freeze({
  'list:project.read': 'visibleProjectsCondition',
  'list:org.read': 'visibleOrganizationsCondition',
});
