// The gems of Qualor's RuboCop pass (plan 9B): RuboCop and what it runs on (gems/, installed from
// tools/analyzers/rubocop/gems.lock) and racc, the one of Ruby's bundled gems install-rubocop.sh
// keeps (ruby/lib/ruby/gems/<abi>/), each with the licence files it ships. Fails on a licence
// outside ALLOWED. Writes deploy/scanner/licenses/RUBOCOP-DEPENDENCIES.txt. Run where the pass is
// installed (the analyzers toolbox):
//   node tools/analyzers/rubocop/licences.mjs [/opt/qualor/rubocop] [output file]
import { existsSync, readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

export const ALLOWED = new Set(['MIT', 'Ruby', 'BSD-2-Clause']);
const LICENCE_FILE = /^(licen[cs]e|copying|bsdl|legal|mit-licen[cs]e)/i;

/** The licence ids of an installed gemspec (`s.licenses = ["Ruby".freeze, "BSD-2-Clause".freeze]`). */
export function gemspecLicences(text) {
  const list = /^\s*s\.licenses = \[(.*)\]\s*$/m.exec(text);
  if (list !== null) return [...list[1].matchAll(/"([^"]+)"/g)].map((m) => m[1]);
  const one = /^\s*s\.license = "([^"]+)"/m.exec(text);
  return one === null ? [] : [one[1]];
}

/** Installed gems of one gem directory: name, version, licences and directory. */
function gemsIn(gemDir, only) {
  const specs = path.join(gemDir, 'specifications');
  return readdirSync(specs)
    .filter((f) => f.endsWith('.gemspec'))
    .map((f) => {
      const full = f.slice(0, -'.gemspec'.length);
      const dash = full.lastIndexOf('-');
      return {
        name: full.slice(0, dash),
        version: full.slice(dash + 1),
        licences: gemspecLicences(readFileSync(path.join(specs, f), 'utf8')),
        dir: path.join(gemDir, 'gems', full),
      };
    })
    .filter((g) => only === undefined || only.includes(g.name));
}

/** Orders gems by name, by UTF-16 code units (not by locale). */
function byName(a, b) {
  if (a.name === b.name) return 0;
  return a.name < b.name ? -1 : 1;
}

/** The text of RUBOCOP-DEPENDENCIES.txt for the pass installed at `rubocopDir`. */
export function dependenciesText(rubocopDir) {
  const abi = readdirSync(path.join(rubocopDir, 'ruby/lib/ruby/gems'))[0];
  const gems = [
    ...gemsIn(path.join(rubocopDir, 'gems')),
    ...gemsIn(path.join(rubocopDir, 'ruby/lib/ruby/gems', abi), ['racc']),
  ].sort(byName);
  const problems = gems
    .filter((g) => g.licences.length === 0 || !g.licences.some((l) => ALLOWED.has(l)))
    .map((g) => `${g.name} ${g.version}: ${g.licences.join(', ') || 'no licence declared'}`);
  if (problems.length > 0) throw new Error(`disallowed licences:\n${problems.join('\n')}`);
  const bar = '='.repeat(78);
  const sections = gems.map((g) => {
    const files = existsSync(g.dir)
      ? readdirSync(g.dir)
          .filter((f) => LICENCE_FILE.test(f) && statSync(path.join(g.dir, f)).isFile())
          .sort()
      : [];
    const lines = [bar, `${g.name} ${g.version} (${g.licences.join(' OR ')})`];
    if (files.length === 0)
      lines.push('', '(the gem ships no licence file; its licence is the one named above)');
    for (const f of files)
      lines.push('', `--- ${f}`, readFileSync(path.join(g.dir, f), 'utf8').trimEnd());
    return lines.join('\n');
  });
  return [
    'The gems of Qualor’s RuboCop pass in /opt/qualor/rubocop (RuboCop and what it runs on, installed',
    'from tools/analyzers/rubocop/gems.lock, and racc, the one of Ruby’s bundled gems it keeps), each',
    'with the licence files it ships. Generated by tools/analyzers/rubocop/licences.mjs; do not edit.',
    '',
    ...sections,
    '',
  ].join('\n');
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const here = path.dirname(fileURLToPath(import.meta.url));
  const dir = process.argv[2] ?? '/opt/qualor/rubocop';
  const out =
    process.argv[3] ?? path.join(here, '../../../deploy/scanner/licenses/RUBOCOP-DEPENDENCIES.txt');
  writeFileSync(out, dependenciesText(dir));
  console.log(`wrote ${out}`);
}
